# Generated by Django 5.2.8 on 2025-11-24 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=128)),
                ('utm_medium', models.CharField(blank=True, max_length=128)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('utm_term', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ('-last_visit',),
                'indexes': [models.Index(fields=['last_visit'], name='analytics_v_last_vi_2f4d8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=255)),
                ('section_id', models.CharField(db_index=True, max_length=64)),
                ('visible_ratio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_views', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Просмотр секции',
                'verbose_name_plural': 'Просмотры секций',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['page_path', 'section_id'], name='analytics_s_page_pa_f9827d_idx'), models.Index(fields=['section_id', 'created_at'], name='analytics_s_section_9c2e22_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['page_path', 'created_at'], name='analytics_p_page_pa_8f4c2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FreeLessonLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_slug', models.CharField(db_index=True, max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(db_index=True, default='free_lesson_popup', max_length=64)),
                ('is_valid_number', models.BooleanField(default=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_lesson_leads', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Лид бесплатного урока',
                'verbose_name_plural': 'Лиды бесплатного урока',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'created_at'], name='analytics_f_phone_510165_idx')],
            },
        ),
        migrations.CreateModel(
            name='FailedLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_slug', models.CharField(db_index=True, max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_leads', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Незавершённый лид',
                'verbose_name_plural': 'Незавершённые лиды',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'created_at'], name='analytics_f_event_c896e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=255)),
                ('event_id', models.CharField(db_index=True, max_length=64)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Событие клика',
                'verbose_name_plural': 'События кликов',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_id', 'created_at'], name='analytics_c_event_i_21b6af_idx'), models.Index(fields=['page_path', 'event_id'], name='analytics_c_page_pa_5d55f7_idx')],
            },
        ),
    ]
